### ISSUE TITLE
Decide on logging mechanism

### ISSUE THREAD

**Issue by wtgee** [AstroHuntsman/huntsman-mocks#28]
We probably don't want to have print statements and `verbose` flags all over this repository so need to decide on a common logging mechanism to use.

The standard python logging is sufficient it's mostly just a question of figuring out where to put log files, etc.

@lspitler any thoughts on what you would like to see? I'm unsure if we will need something just for debugging/testing purposes or you would actually like to have logs to refer back to for any reason.

Brought up as part of #26.

**Comment by bazkiaei** [comment]
The logging system is established but not completed yet. We decided not to spend more time on it at the moment.
