### ISSUE TITLE
Should the output of `mocks.create_mock_galaxy_noiseless_image` have unit? 

### ISSUE THREAD

**Issue by bazkiaei** [AstroHuntsman/huntsman-mocks#32]
The output of the function `mocks.create_mock_galaxy_noiseless_image` is `CCDData` and has unit of `electron / (pixel * second)`. Is that a suitable unit for the function's output? Or maybe we want it to be unitless?

**Comment by lspitler** [comment]
@bazkiaei check that this was done and close if you can.

**Comment by bazkiaei** [comment]
Done in #35
