### ISSUE TITLE
Creating `conftest.py`.

### ISSUE THREAD

**Issue by bazkiaei** [AstroHuntsman/huntsman-mocks#36]
@wtgee has suggested that I should create `conftest.py` for the Huntsman Mocks Image Generator. I opened this issue to talk about what we need to do in `conftest.py`. Here is a list of what we know as far:

- The path to the fits file for `test_mocks.py` as a fixture.

**Comment by lspitler** [comment]
This was done in Issue by @wtgee . Closing.
