### ISSUE TITLE
Inconsistencies among the functions of `mocks.py`

### ISSUE THREAD

**Issue by bazkiaei** [AstroHuntsman/huntsman-mocks#70]
There are some inconsistencies between the functions of `mocks.py`. For instance functions `scale_light_by_distance` and `prepare_mocks` both use the distance to the galaxy to scale its light. 
The first step to create the main function is making all functions consistent.

_Originally posted by @bazkiaei in https://github.com/AstroHuntsman/huntsman-mocks/pull/69_

**Comment by AnthonyHorton** [comment]
I don't really understand the issue here. Can't you just copy the code from your example notebook and drop it into a main function in `mocks.py`, with a few minor changes? The notebook unfortunately doesn't render in GitHub so I can't easily look at it.

**Comment by bazkiaei** [comment]
> I don't really understand the issue here. Can't you just copy the code from your example notebook and drop it into a main function in `mocks.py`, with a few minor changes? The notebook unfortunately doesn't render in GitHub so I can't easily look at it.

Yes, I can and I will, but first need to finish the PR #69 .

**Comment by bazkiaei** [comment]
And I should make sure that the functions are consistent.

**Comment by bazkiaei** [comment]
With respect to input data that we have at the moment, all inconsistencies are removed.
