### ISSUE TITLE
Dividing `prepare_mocks` and creating new functions.

### ISSUE THREAD

**Issue by bazkiaei** [AstroHuntsman/huntsman-mocks#74]
This function is doing 4 unrelated things. I would suggest splitting this into at least three functions.

The first function fully parses the config, i.e. loads the config file with `mocks.utils.load_yaml_config`, then goes through _all_ the parameters (not just `galaxy_coordinates` & `observation_time` as now) and applies any keyword arguments that override the config file values, gets the remaining values from the config file, adds default values for any parameters that are missing, and does any required unit conversions, etc.  This function returns the fully populated, validated config dict for all the other functions to use.  The other functions then don't have to do any fiddling around with overriding values, default values, unit conversions, etc.

The second function takes the config as its only argument, loads the simulation data, and returns it. This would be the place to do 32 bit to 64 bit float type conversion, when required.

The calls to `compute_total_mass` and `compute_apparent_ABmag` also don't belong here.  You could create a 3rd function that calls them, using values from `config`,  and returns the results, or you could do those calls in the main function.

The general principle here is that a function should do one clearly defined thing, the thing that the function name implies that it does. Adding other, unrelated things to a function makes it much harder to understand the software.

_Originally posted by @AnthonyHorton in https://github.com/AstroHuntsman/huntsman-mocks/pull/69_

**Comment by lspitler** [comment]
Related to #70 WIP.

**Comment by bazkiaei** [comment]
The function `prepare_mocks` is divided into some other functions but still left as "comment" in the code. The reason is that I think maybe we want to try the code on some fits file and there are some clues in this function about how to do it.
