### ISSUE TITLE
providing jupyter notebook flow for the code.

### ISSUE THREAD

**Issue by bazkiaei** [AstroHuntsman/huntsman-mocks#76]
Really not sure if this function (`read_genesis`) is necessary if it only ends up breaking up the pybody structure. Better to keep things in tact... but maybe the problem is that I don't know your workflow - I need to see the jupyter notebook to understand how this function fits into the flow.

_Originally posted by @lspitler in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTczMjU3ODA0OnYy/pull_request_review_threads/discussion_

**Comment by lspitler** [comment]
addressed in #71 closing.
